[build-system]
requires = ["uv_build>=0.11.8,<0.12"]
build-backend = "uv_build"

[project]
name = "dj-tui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flx4py>=0.1.0",
    "sounddevice>=0.5.5",
    "soundfile>=0.13.1",
    "textual>=8.2.5",
    "textual-dev>=1.8.0",
    "textual-fspicker>=1.0.0",
]

[project.scripts]
dj-tui = "dj_tui.ui:main"

[tool.ruff]
show-fixes = true

[tool.ruff.lint]
select = [
    "F",  # Pyflakes
    "E",  # Pycodestyle
    "W",  # Pycodestyle
    "D",  # Pydocstyle
    "UP",  # pyupgrade
    "I",  # isort
    "PL",  # Pylint
]
ignore = [
    "D203",  # incorrect-blank-line-before-class
    "D213",  # multi-line-summary-second-line
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
